<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-CSN9D3G5" failures="1" tests="3" name="com.actitime.testscript.CustomerModule" time="20.364" errors="0" timestamp="2025-09-30T14:08:25 IST" skipped="0">
  <testcase classname="com.actitime.testscript.CustomerModule" name="deleteCustomer" time="7.036">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.actitime.testscript.CustomerModule.deleteCustomer(CustomerModule.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="com.actitime.testscript.CustomerModule" name="modifyCustomer" time="6.806">
    <system-out>
      <![CDATA[modifyCustomer
modifyCustomer test case is success.]]>
    </system-out>
  </testcase> <!-- modifyCustomer -->
  <testcase classname="com.actitime.testscript.CustomerModule" name="createCustomer" time="6.522">
    <system-out>
      <![CDATA[createCustomer
createCustomer test case is success.]]>
    </system-out>
  </testcase> <!-- createCustomer -->
  <system-out>
    <![CDATA[openBrowser
login
createProject
createProject test case is success.
logout
login
logout
login
modifyProject
modifyProject test case is success.
logout
closeBrower
openBrowser
login
createCustomer
createCustomer test case is success.
logout
login
logout
login
modifyCustomer
modifyCustomer test case is success.
logout
closeBrower
openBrowser
login
createUser
createUser test case is success.
logout
login
logout
login
modifyUser
modifyUser test case is success.
logout
closeBrower]]>
  </system-out>
</testsuite> <!-- com.actitime.testscript.CustomerModule -->
